version: "3.8"
services:
  backend:
    image: jainrounak6/mern-sampleapp:backend
    container_name: mern-backend
    env_file:
      - /opt/elasticbeanstalk/deployment/env.list
    ports:
      - 4000:4000

  frontend:
    image: jainrounak6/mern-sampleapp:frontend
    container_name: mern-frontend
    env_file:
      - /opt/elasticbeanstalk/deployment/env.list
    ports:
      - 8080:8080
    depends_on:
      - backend

  nginx:
    image: jainrounak6/mern-sampleapp:nginx
    container_name: mern-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
